name: Deploy to VPS

on:
  push:
    branches: [ main ] # Запускать развертывание при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }} # IP-адрес вашего VPS
          username: ${{ secrets.VPS_USER }} # Имя пользователя для VPS
          key: ${{ secrets.VPS_SSH_KEY }} # Секрет с приватным SSH-ключом
          script: |
            cd /var/www/experiment
            git pull origin main
            source venv/bin/activate  # Активируем виртуальное окружение
            pip install -r requirements.txt  # Обновляем зависимости если они изменились
            deactivate
            sudo systemctl restart experiment.service